# Overwrite variables for franklin XT4 @ NERSC

BLAS = 
LAPACK =  
SCALAPACK = 
PAPI_INC = ${PAPI_INCLUDE_OPTS}  
PAPI = ${PAPI_POST_LINK_OPTS} 
BLACS = 
NETCDF = ${NETCDF_INCLUDE_OPTS} ${NETCDF_POST_LINK_OPTS} -lnetcdf 
BOUNDS = 
WARN = 
DEBUG = 
DOUBLE = -Mr8
F90 = ftn -fast #-gopt -Mbounds -Mchkfpstk -Mchkptr
MOD_LOC = -module mod
